const majors = [
    "Accounting",
    "Aerospace Engineering",
    "African American Studies",
    "American Studies",
    "Anthropology",
    "Architecture",
    "Art",
    "Art History",
    "Asian Studies",
    "Biochemistry",
    "Bioinformatics and Computational Biology",
    "Biological Sciences",
    "Biomedical Engineering",
    "Biomedical Sciences",
    "Biotechnology",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classics",
    "Cognitive Science",
    "Communication",
    "Computational Linguistics",
    "Computational Physics",
    "Computer Engineering",
    "Computer Science",
    "Criminology",
    "Dance",
    "Economics",
    "Electrical Engineering",
    "Engineering Physics",
    "Engineering Science",
    "English",
    "Environmental Design",
    "Environmental Engineering",
    "Environmental Science",
    "Environmental Studies",
    "Environmental Sustainability",
    "Exercise Science",
    "Film Studies",
    "French",
    "Geographic Information Science",
    "Geography",
    "Geological Sciences",
    "German",
    "Global Affairs",
    "Global Gender Studies",
    "Health and Human Services",
    "History",
    "Industrial Engineering",
    "Information Technology and Management",
    "International Studies",
    "International Trade",
    "Italian",
    "Jewish Studies",
    "Law",
    "Legal Studies",
    "Linguistics",
    "Material Science and Engineering",
    "Mathematics",
    "Mechanical Engineering",
    "Media Study",
    "Medical Laboratory Science",
    "Music",
    "Music Theatre",
    "Neuroscience",
    "Nuclear Medicine Technology",
    "Nursing",
    "Nursing RN to BS",
    "Nutrition Science",
    "Occupational Therapy",
    "Pharmaceutical Sciences",
    "Pharmacology and Toxicology",
    "Pharmacy",
    "Philosophy",
    "Philosophy, Politics and Economics",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health",
    "Sociology",
    "Spanish",
    "Special Studies",
    "Speech and Hearing Science",
    "Statistics",
    "Theatre",
    "Urban and Public Policy Studies"
  ];
  
  export default majors;
  